env:
  global:
    CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
- docker
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
jobs:
  include:
    script:
      - stage: setup
        script: bash ci/setup.sh
      - stage: build
        script: bash ci/build.sh
      - stage: deploy
        script: bash ci/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_86e0ec7377c5_key -iv $encrypted_86e0ec7377c5_iv
  -in google-service-account-creds.json.enc -out google-service-account-creds.json
  -d
