language: bash
env:
  global:
    CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
- docker
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
jobs:
  include:
    - name: "Setup"
      script: 
        - bash scripts/setup.sh
    - name: "Build"
      script: 
        - bash scripts/build.sh
    - name: "Deploy"
      script: 
        - bash scripts/deploy.sh
before_install:
- ls -l
- openssl aes-256-cbc -K $encrypted_86e0ec7377c5_key -iv $encrypted_86e0ec7377c5_iv
  -in google-service-account-creds.json.enc -out google-service-account-creds.json
  -d
