{{- if .Values.certificates.enabled -}}
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: {{ include "flask-hello-world.fullname" . }}
spec:
  domains:
    {{- range .Values.certificates.hosts }}
    - {{ . }}
    {{- end }}
{{- end}}